// Auto-generated by scripts/download-dish-images.mjs
// Placeholder — will be overwritten when download completes
export type DishImageEntry = {
  id: string;
  names: string[];
  cuisine: string;
  card: string;
  hero: string;
};

export const dishImageDb: DishImageEntry[] = [];
